### ISSUE TITLE
Portal Network TODO list

### ISSUE THREAD

**Issue by acolytec3** [acolytec3/portalnetwork#1]
# Portal Network: Client Functionality
 Issue to better track the implemented features in the portal network module, in order to know what to work in still and to have a
 
 ## List of features from document
 Document with listed features that are required can be found at https://notes.ethereum.org/8LbisMwtR4yK64SBosb_2g
 
 * [x]   A - Base Protocol
   * [x]   A.1 - Base Protocol TALKREQ and TALKRESP
   * [x]   A.2 - TALKREQ/TALKRESP message routing
   * [x]   A.3 - TALKREQ/TALKRESP request and response handling
 
 * [ ]   B - Sub Protocol Messages
   * [ ]   B.1 - PING & PONG
     * [ ]   B.1.a - PING message support     
       * [ ]   B.1.a.1 - PING sending
       * [ ]   B.1.a.2 - PING receiving
   * [ ]   B.1.b - PONG message support     
     * [ ]   B.1.b - PONG message support      
       * [ ]   B.1.b.1 - PONG sending
       * [ ]   B.1.b.2 - PONG receiving
   * [ ]   B.1.c - PONG when PING'd
 * [ ]   B.2 - FINDNODES & FOUNDNODES  
   * [ ]   B.2.a - FINDNODES message support    
     * [ ]   B.2.a.1 - FINDNODES sending
     * [ ]   B.2.a.2 - FINDNODES receiving
   * [ ]   B.2.b - FOUNDNODES message support    
     * [ ]   B.2.b.1 - FOUNDNODES message support
     * [ ]   B.2.b.1 - FOUNDNODES sending
     * [ ]   B.2.b.2 - FOUNDNODES receiving
   * [ ]   B.2.c - Serving FINDNODES
 * [ ]   B.3 - FINDCONTENT & FOUNDCONTENT   
   * [ ]   B.3.a - FINDCONTENT message support     
     * [ ]   B.3.a.1 - FINDCONTENT sending
     * [ ]   B.3.a.2 - FINDCONTENT receiving
   * [ ]   B.3.b - FOUNDCONTENT message support     
     * [ ]   B.3.b.1 - FOUNDCONTENT sending
     * [ ]   B.3.b.2 - FOUNDCONTENT receiving
 * [ ]   B.4 - OFFER/ACCEPT/~STORE~  
   * [ ]   B.4.a - OFFER message support    
     * [ ]   B.4.a.1 - OFFER sending
     * [ ]   B.4.a.2 - OFFER receiving
   * [ ]   B.4.b - ACCEPT message support    
     * [ ]   B.4.b.1 - ACCEPT sending
     * [ ]   B.4.b.2 - ACCEPT receiving
   * [ ]   ~B.4.c - STORE message support~
     * [ ]   ~B.4.c.1 - STORE sending~
     * [ ]   ~B.4.c.2 - STORE receiving~
 * [ ]   C - ENR Database: Management of known ENR records
   **Note:** This database is only a requirement if you only store NodeId in the routing table and need a mapping from that NodeId to other ENR information. Our implementation stores the full ENR in the routing table and thus we don't require this. The underlying features are still needed of course, but those we have.
   
   * [x]   C.1 - ENR handling    
     * [x]   C.1.a - Extraction of IP address and port
   * [x]   C.2 - Store ENR record:  ENR records can be saved for later retrieval.    
     * [x]   C.2.a - Tracking highest sequence number
   * [x]   C.3 - Retrieve ENR Record: ENR records can be retrieved by their `node_id`.

 * [ ]   D - Overlay Routing Table 
   * [ ]   D.1 - Distance Function
   * [ ]   D.2 - Manage K-Buckets   
     * [ ]   D.2.a - Insertion of new nodes
     * [ ]   D.2.b - Removal of nodes
     * [ ]   D.2.c - Maximum of K nodes per bucket
     * [ ]   D.2.d - Replacement cache
   * [ ]   D.3 - Retrieve nodes at specified log-distance
   * [ ]   D.4 - Retrieval of nodes ordered by distance to a specified `node_id`
 * [ ]   E - Overlay Network Management: Functionality related to managing a node's view of the overlay network.  
   * [ ]   E.1 - Bootstrapping via bootnodes: The client uses a set of bootnodes to acquire an initial view of the network.
   * [ ]   E.1.a - Bootnodes
     The client has access to a set of bootnodes ENR records.  These records can be either hard coded into the client or provided via client configuration.
   * [ ]   E.2 - Population of routing table
   * [ ]   E.3 - Liveliness checks
   * [ ] 
 * [ ]   F - Content Database:  Management of stored content.
   * [ ]   F.1 - Content can be stored
     Content can be stored in the database
   * [ ]   F.2 - Content can be retrieved by `content_id`
     Given a known `content_id` the corresponding content payload can be retrieved.
   * [ ]   F.3 - Content can be removed
     Content can be removed.
   * [ ]   F.3 - Query furthest by distance
     Retrieval of the content from the database which is furthest from a provided `node_id`.
   * [ ]   F.4 - Total size of stored content
     Retrieval of the total number of bytes stored.
 * [ ]   G - Content Management
   * [ ]   G.1 - Enforcement of maximum stored content size
     When the total size of stored content exceeds the configured maximum content storage size the content which is furthest from the local `node_id` is evicted.
   * [ ]   G.2 - Proof handling  
     * [ ]   G.2.a - Proof Transmission      
       * [ ]   G.2.a.1 - Proof Encoding and Serialization
         The ability to take a merkle proof against the hexary patricia trie and serialize it to a stream of bytes suitable for transmission.
       * [ ]   G.2.a.2 - Proof Decoding and Deserialization
         The ability to take a stream of bytes representing a merkle proof against the hexary patricia trie and deserialize it into a native representation.
     * [ ]   G.2.b - Proof validation
       The ability to validate that a given merkle proof is well formed against a known state root.
     * [ ]   G.2.c - Proof storage
       For each proof, the client should be able to store the proof for later retrieval.
     
     Efficient storage will require the ability to merge multiple proofs into a single proof, and then to extract a minimal sub-proof from the merged proofs.
     A simple model for storage would be simply to store the serialized versions which will result in larger storage overhead, but side-steps the need for merging proofs.
   * [ ]   G.3 - Gossip via OFFER/ACCEPT/~STORE~
     Support for the base gossip protocol implemented on top of OFFER/ACCEPT/~STORE~ messages.
     
     * [ ]   G.3.a - Handle incoming gossip
       Client can listen for incoming OFFER messages, responding with an ACCEPT message for any offered content which is of interest to the client.  ~The client would then listen for the corresponding STORE request which will either contain the full payload in the case that it fits within the packet, **or** extract the `connection_id` for use with a uTP based data stream between the two nodes.~
       Upon receiving the content payload which should be a merkle proof against a leaf of the trie, the proof should be verified, the content stored.
     * [ ]   G.3.b - Propogate incoming gossip
       Upon receiving and validating content from an OFFER/ACCEPT/~STORE~ set of messages, the content should then be gossiped to some set of neighboring peers using the same mechanism.
   * [ ]   G.4 - Serving Content
     The client should listen for FINDCONTENT messages.
   
   When a FINDCONTENT message is received either the requested content or the nodes known to be closest to the content are returned via a FOUNDCONTENT message.
 * [ ]   H - JSON-RPC
   Endpoints that require state access
   
   * [ ]   H.1 - `eth_balance`: TODO
   * [ ]   H.2 - `eth_getTransactionCount`: TODO
   * [ ]   H.3 - `eth_getCode`: TODO
   * [ ]   H.4 - `eth_getStorage`: TODO
   * [ ]   H.5 - `eth_call`: TODO
   * [ ]   H.6 - `eth_estimateGas`: TODO
 
 # uTP support
 * [ ]   B.4.b.1.a - ACCEPT send: set-up uTP stream
 * [ ]   B.4.b.2.a - ACCEPT receive: set-up uTP stream

 * [ ]  I - uTP protocol support 
   * [ ]  I.1 - uTP protocol implementation: [Implement uTP protocol
   * [ ]  I.2 - uTP protocol discv5 integration (over talkreq/talkresp)
 
Note: webRTC transport layer support - needs to be added at the discv5 layer and not in the portal network module
